export const msg_template = {
  _class: "xxx.shopping.infra.repository.mongodb.newsfeed.v3.xxxxx",
  brandName: "23개 브랜드",
  category: "BRAND",
  createDate: null,
  feedType: "FEED_SLIDE_NEWS",
  imageUrl: "https://xxx.shopping.com/xxx/xxx/xxx.jpg",
  isDelete: false,
  isOpen: false,
  isTop: false,
  memberUid: Long("99999999"),
  msg: "쇼핑몰 입니다.",
  originLink:
    "https://xxx.shopping.com/xxx/xxx/xxx/9999?m_request_key=99999999",
  requestKey: "9999999999999999999999999",
  subCategory: "BRAND_NEWS",
  thumbImage: "https://xxx.msscdn.net/xxx/xxx/xxx.png",
  titleCode: "BRAND_NEWS",
  updateDate: null,
};
